SELECT ProductKey,
    ProductAlternateKey,
    ProductSubcategoryKey,
    WeightUnitMeasureCode,
    SizeUnitMeasureCode,
    EnglishProductName,
    SpanishProductName,
    FrenchProductName,
    StandardCost,
    FinishedGoodsFlag,
    Color,
    SafetyStockLevel,
    ReorderPoint,
    ListPrice,
    ChineseDescription,
    ArabicDescription,
    HebrewDescription,
    ThaiDescription,
    GermanDescription,
    JapaneseDescription,
  
    EndDate,
    
    [Status]
FROM AdventureWorksDW2019.dbo.DimProduct